# Generated by Django 5.2.11 on 2026-06-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_tasks_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
